---
- hosts: all
  remote_user: root

  vars:
      # you can override these vars from command line like this:
      #
      # ansible-playbook -e 'sudoUser=bill ntpCountry=fr'
      #
      rootEmail: ""  # who receives root's emails
      timezone: "Europe/London"
      ntpCountry: "uk"  # used for NTP config
      sudoUser: ""
      sudoTimeout: 30  # sudo timeout in minutes (set to -1 to disable timeout)
      gitConfigName: ""
      gitConfigEmail: ""

  tasks:

  - name: check that all required vars have been set
    assert:
      that:
        - "rootEmail != ''"
        - "sudoUser != ''"
        - "gitConfigName != ''"
        - "gitConfigEmail != ''"

  - name: selinux - check if enabled
    command: /usr/sbin/selinuxenabled
    register: seLinuxEnabled
    ignore_errors: yes
    changed_when: False

  - name: yum - install libselinux-python
    yum: name=libselinux-python state=installed
    when: seLinuxEnabled.rc == 0

  - name: yum - update everything
    yum: name=* state=latest

  - name: OpenSSH - disable password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "PasswordAuthentication no"
      regexp: "^PasswordAuthentication "
      insertafter: "^#PasswordAuthentication "
    notify: restart sshd

#   **TODO** set root password to a random string and display it to STDOUT

  - name: OpenSSH - disable GSSAPI auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "GSSAPIAuthentication no"
      regexp: "^GSSAPIAuthentication "
      insertafter: "^#GSSAPIAuthentication "
    notify: restart sshd

  - name: OpenSSH - disable challenge response auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "ChallengeResponseAuthentication no"
      regexp: "^ChallengeResponseAuthentication "
      insertafter: "^#ChallengeResponseAuthentication "
    notify: restart sshd

  - name: yum - install epel-release RPM package
    yum: pkg=epel-release state=installed

  - name: yum - install useful RPM packages
    yum: pkg="{{ item }}" state=installed
    with_items:
       - bash-completion
       - bind-utils
       - curl
       - dos2unix
       - git
       - iotop
       - jwhois
       - lsof
       - lynx
       - mailx
       - man
       - nmap
       - ntp
       - ntpdate
       - rsync
       - tcpdump
       - telnet
       - traceroute
       - unix2dos
       - unzip
       - vim-enhanced
       - wget
       - yum-cron
       - zip

  - name: /etc/aliases - setup root email alias to {{ rootEmail }}
    lineinfile:
        dest: /etc/aliases
        backup: yes
        line: "root:          {{ rootEmail }}"
        regexp: "^root:"
        insertafter: "^#root:"
    notify: update aliases database

  - name: yum-cron - start and enable
    service: name=yum-cron state=started enabled=yes

  - name: timezone config - /etc/sysconfig/clock
    lineinfile:
      dest: /etc/sysconfig/clock
      backup: yes
      line: 'ZONE="{{ timezone }}"'

  - name: timezone config - /etc/localtime symlink
    file: src=../usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

  - name: ntpd - config for {{ ntpCountry }}.pool.ntp.org
    lineinfile:
      dest: /etc/ntp.conf
      backup: yes
      line: "server {{ item }}.{{ ntpCountry }}.pool.ntp.org iburst"
      regexp: "^server {{ item }}.{{ ntpCountry }}.pool.ntp.org "
      insertafter: "^server "
    with_items:
      - "0"
      - "1"
      - "2"
      - "3"

  - name: ntpd - start and enable
    service: name=ntpd state=started enabled=yes

  - name: ".config files - copy to /etc/skel"
    copy: src="files/" dest="/etc/skel/" owner=root group=root mode=0644
    with_items: userConfigFiles

  - name: ".config files - copy to /root"
    copy: src="files/" dest="/root/" owner=root group=root mode=0644
    with_items: userConfigFiles

  # **TODO**: iptables config

  - name: vim - create /root/.vim/
    file: name="/root/{{ item }}" state=directory owner=root group=root mode=0700
    with_items:
        - ".vim/swap"
        - ".vim/backup"

  - name: vim - create /etc/skel/.vim/
    file: name="/etc/skel/{{ item }}" state=directory owner=root group=root mode=0700
    with_items:
        - ".vim/swap"
        - ".vim/backup"

  - name: user '{{ sudoUser }}' - create and add to 'wheel' group
    user: name={{ sudoUser }} append=yes groups=wheel

  - name: sudo - allow wheel group to use sudo
    lineinfile:
        dest: /etc/sudoers
        regexp: "^%wheel"
        line: "%wheel  ALL=(ALL)       ALL"
        validate: 'visudo -cf %s'

  # default sudo timeout is 5 mins
  - name: sudo - set timeout to {{ sudoTimeout }} mins
    lineinfile:
        dest: /etc/sudoers
        line: "Defaults    timestamp_timeout={{ sudoTimeout }}"
        regexp: "^Defaults +timestamp_timeout=[0-9]+ *$"
        insertafter: "Defaults +env_reset"
        validate: 'visudo -cf %s'

  - name: .gitconfig - template over for {{ sudoUser }}
    template: src="templates/.gitconfig.j2" dest="~{{ sudoUser }}/.gitconfig" owner="{{ sudoUser }}" group="{{ sudoUser }}" mode=0600

  handlers:
    - name: update aliases database
      command: newaliases

    - name: restart sshd
      service: name=sshd state=restarted
