---
- hosts: all
  remote_user: root

  vars:
      root_email: ben@kennish.net
      timezone: "Europe/London"
      ntpCountry: "uk"  #used for NTP config

  tasks:
  #- name: yum update everything
  #  yum: name=* state=latest

  - name: OpenSSH - disable password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "PasswordAuthentication no"
      regexp: "^PasswordAuthentication "
      insertafter: "^#PasswordAuthentication "
    notify: restart sshd

#   set root password to random string?

  - name: OpenSSH - disable GSSAPI auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "GSSAPIAuthentication no"
      regexp: "^GSSAPIAuthentication "
      insertafter: "^#GSSAPIAuthentication "
    notify: restart sshd

  - name: OpenSSH - disable challenge response auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "ChallengeResponseAuthentication no"
      regexp: "^ChallengeResponseAuthentication "
      insertafter: "^#ChallengeResponseAuthentication "
    notify: restart sshd

  - name: install yum packages
    yum: pkg={{ item }} state=latest
    with_items:
      - vim-enhanced
      - man
      - git
      - bind-utils
      - curl
      - dos2unix
      - unix2dos
      - iotop
      - jwhois
      - lsof
      - lynx
      - mailx
      - nmap
      - ntp
      - ntpdate
      - rsync
      - telnet
      - tcpdump
      - wget
      - yum-cron
      - zip
      - unzip
      - traceroute
      - bash-completion
      - epel-release

  - name: root email alias to {{ root_email }}
    lineinfile:
        dest: /etc/aliases
        backup: yes
        line: "root:          {{ root_email }}"
        regexp: "^root:"
        insertafter: "^#root:"
    notify: update aliases database

  - name: start and enable yum-cron
    service: name=yum-cron state=started enabled=yes

  - name: configure timezone (/etc/sysconfig/clock)
    lineinfile:
      dest: /etc/sysconfig/clock
      backup: yes
      line: 'ZONE="{{ timezone }}"'

  - name: configure timezone (/etc/localtime)
    file: src=../usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

  - name: configure NTP
    lineinfile:
      dest: /etc/ntp.conf
      backup: yes
      line: "server {{ item }}.{{ ntpCountry }}.pool.ntp.org iburst"
      regexp: "^server {{ item }}.{{ ntpCountry }}.pool.ntp.org "
      insertafter: "^server "
    with_items:
      - "0"
      - "1"
      - "2"
      - "3"

  - name: start and enable ntpd
    service: name=ntpd state=started enabled=yes

  - name: fetch dot config files (e.g. .bashrc)
    get_url: url=https://get.sysadmin.tools/dotFiles/{{ item }} dest="~/.{{ item }}" mode=0644
    with_items:
      - "bashrc"
      - "vimrc"
      - "gitconfig"

  handlers:
    - name: update aliases database
      command: newaliases

    - name: restart sshd
      service: name=sshd state=restarted
