---
- hosts: all
  remote_user: root

  vars:
      # **TODO**: allow these vars to be set from command line (first to bash, then forward to ansible)
      root_email: "ben@kennish.net"
      timezone: "Europe/London"
      ntpCountry: "uk"  #used for NTP config
      sudoUser: "bill"
      sudoTimeout: 30  # sudo timeout in minutes (set to -1 to disable timeout)

  tasks:
  #- name: yum update everything
  #  yum: name=* state=latest

  - name: OpenSSH - disable password auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "PasswordAuthentication no"
      regexp: "^PasswordAuthentication "
      insertafter: "^#PasswordAuthentication "
    notify: restart sshd

#   **TODO** set root password to a random string

  - name: OpenSSH - disable GSSAPI auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "GSSAPIAuthentication no"
      regexp: "^GSSAPIAuthentication "
      insertafter: "^#GSSAPIAuthentication "
    notify: restart sshd

  - name: OpenSSH - disable challenge response auth
    lineinfile:
      dest: /etc/ssh/sshd_config
      backup: yes
      line: "ChallengeResponseAuthentication no"
      regexp: "^ChallengeResponseAuthentication "
      insertafter: "^#ChallengeResponseAuthentication "
    notify: restart sshd

   - name: install useful RPMs using yum
     yum: pkg={{ item }} state=installed
     with_items:
       - vim-enhanced
       - man
       - git
       - bind-utils
       - curl
       - dos2unix
       - unix2dos
       - iotop
       - jwhois
       - lsof
       - lynx
       - mailx
       - nmap
       - ntp
       - ntpdate
       - rsync
       - telnet
       - tcpdump
       - wget
       - yum-cron
       - zip
       - unzip
       - traceroute
       - bash-completion
       - epel-release

  - name: root email alias to {{ root_email }}
    lineinfile:
        dest: /etc/aliases
        backup: yes
        line: "root:          {{ root_email }}"
        regexp: "^root:"
        insertafter: "^#root:"
    notify: update aliases database

  - name: start and enable yum-cron
    service: name=yum-cron state=started enabled=yes

  - name: configure timezone (/etc/sysconfig/clock)
    lineinfile:
      dest: /etc/sysconfig/clock
      backup: yes
      line: 'ZONE="{{ timezone }}"'

  - name: configure timezone (/etc/localtime)
    file: src=../usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link force=yes

  - name: configure NTP
    lineinfile:
      dest: /etc/ntp.conf
      backup: yes
      line: "server {{ item }}.{{ ntpCountry }}.pool.ntp.org iburst"
      regexp: "^server {{ item }}.{{ ntpCountry }}.pool.ntp.org "
      insertafter: "^server "
    with_items:
      - "0"
      - "1"
      - "2"
      - "3"

  - name: start and enable ntpd
    service: name=ntpd state=started enabled=yes

# do this for all users (modifying /etc/skel?) before creating the ben user?

  - name: setting up user 'dot-config' files (e.g. .bashrc) in /etc/skel
    get_url: url="https://get.sysadmin.tools/dotFiles/{{ item }}" dest="~/.{{ item }}" mode=0644
    with_items:
      - "bashrc"
      - "vimrc"
      - "gitconfig"

  # **TODO**: iptables config

  - name: create directories in home for vim
    file: name="~/{{ item }}" state=directory mode=0700
    with_items:
        - ".vim/swap"
        - ".vim/backup"

  - name: create user '{{ sudoUser }}' and add them to 'wheel' group
    user: name={{ sudoUser }} append=yes groups=wheel

  - name: allow wheel group to use sudo
    lineinfile:
        dest: /etc/sudoers
        line: "%wheel  ALL=(ALL)       ALL"
        regexp: "^#? *%wheel +ALL=(ALL) +ALL"
        validate: 'visudo -cf %s'

  # default sudo timeout is 5 mins
  - name: set sudo timeout to {{ sudoTimeout }} mins
    lineinfile:
        dest: /etc/sudoers
        line: "Defaults    timestamp_timeout={{ sudoTimeout }}"
        regexp: "^Defaults +timestamp_timeout=[0-9]+ *$"
        insertafter: "Defaults +env_reset"
        validate: 'visudo -cf %s'

  handlers:
    - name: update aliases database
      command: newaliases

    - name: restart sshd
      service: name=sshd state=restarted
